# Overview

## Before the Training {-}

* **Please fill out your [registration form](https://forms.gle/fmvJq8oQ7oGur1hn6){target="_blank"}.** This is to gauge participants' backgrounds and interests. Thank you.

* **Ensure you are able to log onto Zoom.** 

* **Please download the data for the qgis turorial ahead of time.** To download the data, please click on the day1_data.zip file that can be found [here](https://github.com/WoodwellRisk/KILA_ToT/tree/main/data){target="_blank"}. Then press the Download button. To access the data and directions for the technical exercise, please download the homework_data.zip file at the same link. 


## Agenda {-}

The training agenda can be found [here](https://github.com/WoodwellRisk/KILA_ToT/blob/main/course_materials/KILA_Climate_Risk_Agenda.pdf){target="_blank"}.


## Powerpoints {-}
After the full training, PDF files of the slides will be shared [here](https://github.com/WoodwellRisk/KILA_ToT/tree/main/course_materials){target="_blank"}.


## Zoom Recordings {-}
The video for the Day 1 session can be found [here](https://woodwellclimate-org.zoom.us/rec/share/WfwCTcTo0PYk82_ZAJ3mIESfidIAb0xdSJ0MTjMURhOVqsEW1-MTXgoEHJOOX2ex.TUCQPe1C8NvuhnAi){target="_blank"}. 
The video for the Day 2 session can be found [here](https://woodwellclimate-org.zoom.us/rec/share/m5CBXt7Rdpw4jB-ZaxOEhF170J_kr3ihGFnHY4L34BwUAWkp3agKYQYpgz4xQRsM._xAztKUczPf13CgK){target="_blank"}. 
You will need to register to view the recordings. 


## Technical Exercise and Map Submission {-}
To access the data and directions for the technical exercise, please click on the homework_data.zip file [here](https://github.com/WoodwellRisk/KILA_ToT/tree/main/data){target="_blank"}. Then press the Download button. 

After completing the technical exercise, please share your maps by using the submission form [here](https://forms.gle/RhcuKB4Wg7jBVgnG7){target="_blank"}. The form will also ask you to describe your maps. Please submit your maps by Monday January 16, 2023.
