# Speaker Bios

<span style="color: #FF7733;">**CHANGE ME**</span> 

## Hosts {-}

**Dr. Alex Naegele**

With an interdisciplinary background in climate science, environmental science, and international development, Dr. Alexandra Naegele studies the impact of climate change on society. Her current work examines climate impacts on a range of scales—from the intersection of climate change and national and regional security to working with under-resourced communities to build their climate resilience.

Dr. Naegele completed a B.S. in Environmental Science from The Ohio State University. After graduating, she served in the Peace Corps and worked on community-based adaptation to climate change in rural Morocco, where communities were facing the challenges of extended drought and extreme rainfall. She returned from the Peace Corps with the goal of bridging the science and the societal impacts of climate change, completing her M.S. and Ph.D. in Atmospheric Science at Colorado State University, where she also earned a graduate certificate in International Development.




**Darcy Glenn**

Darcy Glenn utilizes climate modeling to provide information to decision-makers about the near-term impacts of climate change as part of Woodwell Climate Research Center’s Risk program. She works with both municipalities and business investors who aim to adapt to the changing climate.

Previously,  Darcy worked for two local governments:  Park City, Utah and Summit County, Utah. There she had the privilege to work on the “Most Ambitious Climate Goals in North America” allowing her to work on carbon accounting, wildfire adaptation, regenerative agriculture, and electrification policy. She received her MSc in Climate Change from University College London.




## Speakers {-}

**Carl Churchill**

Carl Churchill is a graphics reporter with The Wall Street Journal. He works primarily on issues relating to climate, ecology, and current events.
He joined the Journal after working as a Cartographer for the Woodwell Climate Research Center, a climate science organization based in Massachusetts. While there, he received recognition for his graphics work on Amazon deforestation and Arctic climate change. He has a master’s in GIS from Arizona State University.




**Abash Paudel**

Abash Paudel has received both his MSc General Forestry and BS Forest Ecology and Biology from Tribhuvan University's Institute of Forestry. He has worked on a variety of projects including the Impact of Climate Variability on Snow Cover in Annaurna Conservation Area. Mr. Paudel is well versed in a variety of geospatial tools including Google Earth Engine and GIS.


